language: elixir
elixir:
  - 1.0.5
otp_release:
  - 18.0
addons:
  postgresql: '9.4'
before_script:
  - mix do ecto.create, ecto.migrate
deploy:
  provider: heroku
  app: square-square-backend
  buildpack: https://github.com/HashNuke/heroku-buildpack-elixir.git
  api_key:
    secure: SXzye22hZbI7lrU8stXXHlelUq/9N2Z/+2BVJ2Hwfm3VCJEgWCDUuijgoBE10VKfAXz1c2P6goyG433n9RlIkvYxSWJW0l9enPyPehd/uPMwP95FiRGjDoVPBjrkbBd+96JcMQdB63lC79OQitphZCyQOpDtOCgqdxzLIJfxYhcEC28RWG3g5lkOkJPHKC3JyUFAeKOBcwQMcRxm3XoikPyx89P/4YDzLXwzW32tTiqm3HqIetqfLC9yGOBirz34j063yFPlpUT6HY88JscY1M5vd15j3OiMLkfwGCENPsQv3Ot3XShY/fdWK0ACaDqFXmWkUFEmFsdOXNmwfXX0AxELra4n8hbGScedwUbCiizwbRwaXESYiMLjJtyW00vyt1ltjbiPPsNjDEQ1zILPpieR2130C680KlTUgezk8BTczg2qrHuXZ8Z2LEGz2aOaezimzt7N8pWjnNx4K/y/LtWQ7EVq/Tc3O/lJCsl7LJn6emauwxm2UkizAmG3ULIORcHZZ0HeES8ieoUl9CTXqR3Lr4xvyOTKdiwiMuGiqVhDPnHojRxhQND8SD1oECurves+9PFPsm/ZadWXOq1TZpjHxxrp2ZXTTKcVdDm/3AKytgx+NV3V5GZXFoLojWadZfXWOJ1r0ZteIsq2urR2v3wGYWWA8LIzAGb+ygXD0Z8=
